name: LearningTodo CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Hämtar repository
        uses: actions/checkout@v7
      - name: Installera .Net 10
        uses: actions/setup-dotnet@v6
        with: 
          dotnet-version: '10.0.x' 
      - name: Restore Dependencies
        run: dotnet restore LearningTodo.Api.slnx
      - name: Build
        run: dotnet build LearningTodo.Api.slnx --no-restore

      - name: Run tests
        run: dotnet test --solution LearningTodo.Api.slnx --no-build
       
         

